package magic.core.cards;

import magic.core.cards.lands.BasicLands;
import magic.core.states.State;
import magic.infrastructure.validation.rules.ValidationRule;

import java.util.Collection;
import java.util.UUID;

public abstract class Harmful extends Card {

    private final int damage;
    private final int maxTargetCount;

    public Harmful(UUID id, String name, int damage,
                   Collection<Properties> properties,
                   Collection<BasicLands> cost) {
        this(id, name, damage, 1, properties, cost);
    }

    public Harmful(UUID id, String name, int damage, int maxTargetCount,
                   Collection<Properties> properties,
                   Collection<BasicLands> cost) {
        super(id, name, properties, cost);
        this.damage = damage;
        this.maxTargetCount = maxTargetCount;
    }

    public int damage() {
        return damage;
    }

    /**
     * @return the base damage plus any increase/decrease
     * generated by any game mechanics such as attachments.
     */
    public int effectiveDamage() {
        return damage();
    }

    public int maxTargetCount() {
        return maxTargetCount;
    }
}
