package org.jmagic.infrastructure;

/**
 * Damageable Interface.
 *
 * @author ldavid
 */
public interface IDamageable extends ITargetable {

    int life();

    /**
     * @return the base life plus any increase/decrease
     * generated by game mechanics such as the attachments.
     */
    int effectiveLife();

    int originalLife();

    /**
     * @return the base max-life plus any increase/decrease
     * generated by game mechanics such as the attachments.
     */
    int effectiveOriginalLife();

    IDamageable takeDamage(int damage);

    /**
     * Checks whether or not this {@link IDamageable} is alive.
     * A common implementation for this method is simply:
     * {@code return effectiveLife() > 0}
     *
     * @return true if alive, false otherwise.
     */
    boolean isAlive();
}
